### PR TITLE
parser optimization step One

### PR DESCRIPTION
**Pull request by niXman**
Hi,

This simple PR speeds up ~13% of parsing time.

Tested using GCC-6.2.0.

### CODE REVIEW

**Comment by niXman** [comment]
Travis is broken? ;)

**Comment by niXman** [comment]
> 100% tests passed, 0 tests failed out of 408

**Comment by niXman** [comment]
ping?

**Comment by lefticus** [comment]
I'm busy with other work right now, I'll get back to ChaiScript pull requests shortly.

**Comment by lefticus** [comment]
What tests are you using to determine parsing time?

**Comment by niXman** [comment]
I used `compiled_tests` and `integer_literal_test` tests.

Callgrind files for original and optimised version in attachments. You can view it using `kcachegrind`.
[chaiscript-callgrind.zip](https://github.com/ChaiScript/ChaiScript/files/601995/chaiscript-callgrind.zip)

**Pull request merged**
