### PR TITLE
Added template specialization in chaiscript::utility::add_class<Enum> to register bulk constants.

### PR DESCRIPTION
**Pull request by vrennert**
I hope you will consider adding this addition to the helper, so people can use them exactly like the user-type / fun combination.

### CODE REVIEW

**Comment by vrennert** [comment]
For some reason the build systems break but i don't see where and how it is related to my changes.

**Comment by lefticus** [comment]
I agree that the build failures are not related to your code. Both travis and appveyor have been giving me a hard time lately. 

That said though, can you please add an example for how to use this code with a small test, similar to this one:

https://github.com/ChaiScript/ChaiScript/blob/64dd349e32d8bd60006aac64ca350b00da40aa6f/unittests/compiled_tests.cpp#L487-L518

Thanks

**Comment by vrennert** [comment]
The script execution does work now with enums inside the shorthand vector and passing it to user defined functions, however for completeness we should look at why returning from the script does construct the correct vector but it seems to be empty in every case i have tried.

    chai.eval<std::vector<Utility_Test_Numbers>>("return [ONE, TWO]");

I have also tried to separately boxed_cast the result which ends up throwing chaiscript::exception::bad_boxed_cast

    auto intermediate = chai.eval("return [ONE, TWO]");
    auto targetVec = chaiscript::boxed_cast<std::vector<Utility_Test_Numbers>>(intermediate);

**Comment by lefticus** [comment]
There are two issues.

1. `return` should only be valid for returning from functions. I'm surprised that code is working at all for you. Instead just do `chai.eval("[ONE, TWO"])` to return the value back into C++. (The return value of any statement is the last value evaluated).
2. There is a memory error related to object lifetimes that I have fixed on a separate branch. I've just merged that branch into my copy of this branch. I've submitted a new pull request back to you to try.

**Pull request merged**
