### PR TITLE
Support scientific notation for floating point (issue #173)

### PR DESCRIPTION
**Pull request by totalgee**
This is in response to (my) issue #173.  It allows for pretty general floating point literals with scientific notation (1e8, -3.7e-200, 55.0E+007), almost like C++'s.  The only difference (I think) is that *if* there is a decimal, there must be some digits after it (that's how it was previous to my changes, and different from C++).  So `1.` is not a valid floating point number in ChaiScript, but `1.0` is (and `1` is an integer, of course).  I added unit tests in float.chai for a bunch of cases, and all existing unit tests still pass with these changes.

Let me know if you'd like things done differently, this is my first contribution to the project...

### CODE REVIEW

**Comment by lefticus** [comment]
@totalgee CI results are coming in. It looks like MSVC doesn't have `std::tolower` implemented or maybe it's just being more pedantic about needing you to `#include <cctype>`

You're welcome to try just the `#include` change first and seeing if that gets it working on Windows. Any changes you make to the PR will automatically be built. 

http://chaiscript.com/ChaiScript-BuildResults/ChaiScript-d762ef08b6d70f2382d9a1ccf5c3c2fed2603c57-PR174-i386-Windows-8.1-VisualStudio-14.html

**Comment by totalgee** [comment]
Thanks, looks like that worked.  It was either that or try <locale>, but <cctype> seems to have done the trick.  This build and test system you've got set up with Travis CI is brilliant, it's the first time I've come across it.

**Comment by lefticus** [comment]
Travis just does a piece of it. The rest is run through my own custom CI
https://github.com/lefticus/decent_ci . It's EXTREMELY CMake/C++/Github
centric. But if that's your setup, it can run on virtually any platform
without having to set up any extra servers besides the machines you want to
build on themselves (it uses github for synchronization)

**Comment by lefticus** [comment]
Looks good now. Merging.

**Pull request merged**
