### PR TITLE
Trying new bash uploading methods

### PR DESCRIPTION
**Pull request by stevepeak**
Please do not merge. Will be trying out some script changes. Thanks

### CODE REVIEW

**Comment by lefticus** [comment]
@stevepeak Sounds good. I noticed one other issue, if you didn't see it - your script assumes "gcov" is the executable to run - but for my g++-4.8 tests I need to run `gcov-4.8` which I'm in the process of waiting for travis to test.

**Comment by stevepeak** [comment]
Perhaps you can help me hack on the bash uploader with your suggestions: https://github.com/codecov/codecov-bash/blob/wip/codecov

**Comment by lefticus** [comment]
@stevepeak I'll give it a shot if this build I'm waiting on works like I hope.

**Comment by lefticus** [comment]
ok, this last commit on my copy of the branch got it working: http://codecov.io/github/ChaiScript/ChaiScript?ref=1586648a02fc0bf63a645bab966312c5b35e491b

https://github.com/ChaiScript/ChaiScript/blob/no_raw_loops/.travis.yml#L27

I'll look at hacking on your script tomorrow.

**Comment by lefticus** [comment]
@stevepeak should we delete this PR now that we got things worked out?

**Comment by stevepeak** [comment]
Yea, we can delete this. I will be publishing head of master branch this afternoon. Thanks for helping me out on this!

**Pull request closed without merging**
