### PR TITLE
Fixes for VS2019 and C++17 compilation

### PR DESCRIPTION
**Pull request by totalgee**
Issue this pull request references: #536 (replaces it)

Changes proposed in this pull request

 - here I've started with @lefticus branch [`VS_2019_fixes`](https://github.com/ChaiScript/ChaiScript/tree/VS_2019_fixes), merged `develop` into it to get up to date with more recent changes, and then added several other required fixes I've discovered are necessary (discussed in my "code review" of #536). Also, the unit test "Object copy counts" now passes again without the special handling for MSVC.

### CODE REVIEW

**Comment by totalgee** [comment]
Regarding the AppVeyor (Windows) unit test failure -- I just changed that very test case to remove the special handling for MSVC...but I guess it's something they changed/fixed between versions (previously an extra copy was made of the object). Your AppVeyor build is running VS2017 and I'm running the latest VS2019. Should I put a more specific version check in the unit test code, rather than just removing it as I did?

**Comment by totalgee** [comment]
Okay, all CI builds and tests working, no warnings (moved AppVeyor to VS2019 to avoid VS2017 bug)... This would be good to merge, I think (and @lefticus' PR #536 can be skipped -- this one builds on it, plus adds more required fixes).

**Comment by RobLoach** [comment]
This is incredible! Nicely done, @totalgee. Saving a manual compiler check with 2019 is great.

**Comment by RobLoach** [comment]
Going to merge! Are there any follow ups that you think we should get in?

**Pull request merged**
