### PR TITLE
Added elapsed time helper to chai executable

### PR DESCRIPTION
**Pull request by totalgee**
Hi there -- just thought I'd throw this your way, in case you want to integrate it...  If not (or if you want me to change the function name), that's fine.

It's handy when doing benchmarking to have some elapsed time functionality built in to the `chai` app.

### CODE REVIEW

**Comment by lefticus** [comment]
@totalgee I like the idea, but it makes me want a more complete solution. Something that lets you get the current date / time / etc, more closely matches the C++ api maybe? I'm going to think about it for a day or two.

**Comment by totalgee** [comment]
Okay, I guess it makes sense to stick closer to the C++ api...  How about I just add a `now()` method, that returns time in seconds as a double (since the *epoch*, whose definition varies by system).  It's not good for time and date, but great for timing things.

Or do you mean to expose all the time stuff in `<chrono>` (like `time_point`, `duration`, various clocks) and date utilities (like `std::localtime()`, `std::put_time()`, `std::locale()`, etc.)?

**Comment by totalgee** [comment]
Okay, I added `now()`, and added a unit test file for performance (which basically runs my silly loop).  The test doesn't pass or fail based on timing results (how could it?), but it does at least exercise the new now() function, and checks that the end result is what we expect.  It can be handy to look at the output in Testing/Temporary/LastTest.log to see how long the loop took to run.

**Comment by totalgee** [comment]
Since the performance can vary quite a bit from one run to the next, you can take the best of several tries (on Linux/OS X at least) by doing something like this:

```bash
(for i in {1..25}; do ctest -R performance -V | grep Elapsed; done) | sort | head -1
```

**Pull request merged**
