### PR TITLE
Critical fix of type_info ordering (less than operator)

### PR DESCRIPTION
**Pull request by stephenberry**
Issue this pull request references: #391 (in part)

Comparing pointers was resulting in random differing behavior between compilations. This fix ensures consistent behavior at least on a given compiler (`before` is implementation specific).

### CODE REVIEW

**Comment by lefticus** [comment]
Is it possible to add a test that somehow illustrates the problem this is solving?

**Comment by stephenberry** [comment]
I found this issue debugging some pretty complex code, but I'll try to make a test case when I get a chance.  

I was able to narrow my testing down to this line of code and consistently get wrong behavior (between compilations) when the code wasn't fixed. But, I'll have to look into making a simple case.

**Comment by lefticus** [comment]
I'm afraid that we risk reintroducing a bug later if we don't understand exactly what was fixed, which is why I don't want this to go without a test... particularly since I cannot think of where this would cause issues.

**Comment by stephenberry** [comment]
I understand. I'll develop a test case when I get a chance.

**Comment by lefticus** [comment]
I'm going to go ahead and merge these even without some kind of additional tests, pre v6.1.0

**Comment by stephenberry** [comment]
Thanks, the code I discovered this issue in is simply too complex for me to dig through right now. I appreciate you merging this fix.

**Pull request merged**
