### PR TITLE
Add test to pass unique_ptr<Derived> to function expecting unique_ptr…

### PR DESCRIPTION
**Pull request by Dalzhim**
Test for a conversion currently not working in ChaiScript.

### CODE REVIEW

**Comment by lefticus** [comment]
These conversions are not possible without causing an unexpected change in meaning to the user.

See this version that takes a `std::unique_ptr<B>`

```
#include <memory>

struct B
{ };

struct D : B
{ };

void take_a_b(std::unique_ptr<B> &&)
{ }

int main()
{
  std::unique_ptr<D> d;
  take_a_b(std::move(d));
  // note, `d` *must* be empty now because it was necessary for the construction
  // of the temporary `std::unique_ptr<B>
}
```

https://godbolt.org/g/R2bjpS

This is only possible if you explicitly move the value in, converting it to an r-value reference, which would cause a temporary of type `std::unique_ptr<B>` to be constructed which takes ownership of the `unique_ptr`.

Compare this to the version that takes a `D`

```cpp
#include <memory>

struct B
{ };

struct D : B
{ };

void take_a_d(std::unique_ptr<D> &&)
{ }

int main()
{
  std::unique_ptr<D> d;
  take_a_d(std::move(d));
  // note, `d` *might* be empty now, but only if the `take_a_b` function
  // does something to explicitly move the value out
  
  // it's important to remember that `std::move` does not actually "move" anything,
  // it's just a cast to an r-value reference
}
```

https://godbolt.org/g/nmwjJv

I'm extremely reluctant to implement this kind of automatic conversion with the subtle change in meaning and the amount of runtime checking it would require to do.

**Comment by Dalzhim** [comment]
You are absolutely right that the implicit creation of a temporary `std::unique_ptr<B>` guarantees that the original variable is moved from. I wouldn't consider it a change in expected behavior though as the function signature makes it explicit that this object will be moved from. Even in the case where a temporary is not implicitly created, it would be unsafe for the caller to assume the argument it provided might not have been moved from.
Then again, if the caller really wants to make sure, the moved from `unique_ptr<D>` can be tested safely has it would hold a `nullptr` in the case it really was moved from (N4296 §20.8.1.4.2).

As far as the amount of runtime checking required to implement that conversion in ChaiScript, you're the expert here so I cannot comment. The only thing I know is that those automatic conversions would be consistent with the pure C++ examples you gave.

The reason I need those conversions is that I am trying to use ChaiScript to create scripts that assemble complex object structures with the engine's building blocks and a lot of these building blocks aren't meant for shared ownership, hence my preference for `unique_ptr<T>`.

If you still feel uneasy about the runtime cost of such a feature, would you consider an option that must be explicitly turned on to activate such automatic conversions? Something that could be turned on with cmake's -D parameter?

**Comment by lefticus** [comment]
The more I think about this, the more I think it's only going to be possible with a user defined `unique_ptr<>` conversion operation. I'm going to spend some time working on this and see what's possible.

**Comment by Dalzhim** [comment]
That sounds great! I'll happily test those changes as soon as you're ready!

**Comment by lefticus** [comment]
I've gone several rounds with this and it's just not something I'm going to be able to get in soon. There's conflicting concepts between implicit and explicit conversions. I think your best bet would be to provide your own explicit function call that takes a `unique_ptr<Derived> &&` and returns a `unique_ptr<Base>` then you could call like `myfunc(myconverter(obj))`

**Comment by RobLoach** [comment]
Feel free to re-open this if desired! :+1:

**Pull request closed without merging**
